version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:2.14.0
    hostname: portainer
    container_name: portainer__portainer

    restart: unless-stopped

    environment:
      - LD_LIBRARY_PATH=/lib64/

    volumes:
      - type: bind
        source: /lib/x86_64-linux-gnu/
        target: /lib64/
        read_only: true

      - type: bind
        source: /usr/local/bin/docker-compose
        target: /docker-compose
        read_only: true

      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

      - type: volume
        source: portainer_data
        target: /data

    expose:
      - 9000

    networks:
      portainer_cloudflared:
      portainer_internet:

    deploy:
      resources:
        limits:
          memory: 256m

    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m


  cloudflared:
    image: cloudflare/cloudflared:2022.7.1
    hostname: cloudflared
    container_name: portainer__cloudflared

    command:
      "tunnel --hostname portainer.yr32.net --url http://portainer:9000 --metrics 0.0.0.0:9126"

    # for 600 cert.pem
    user: root

    depends_on:
      - portainer

    restart: unless-stopped

    volumes:
      - type: bind
        source: ./cert.pem
        target: /etc/cloudflared/cert.pem
        read_only: true

      - type: bind
        source: ./config.yml
        target: /etc/cloudflared/config.yml
        read_only: true

    networks:
      portainer_cloudflared:
      cloudflared_internet:
      prometheus__cloudflared:
        aliases:
          - cloudflared__portainer

    deploy:
      resources:
        limits:
          memory: 128m

    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m

volumes:
  portainer_data:
    name: portainer__portainer_data

networks:
  prometheus__cloudflared:
    name: prometheus__cloudflared
    internal: true
    external: true

  portainer_cloudflared:
    name: portainer__portainer_cloudflared
    internal: true

  portainer_internet:
    name: portainer__portainer_internet

  cloudflared_internet:
    name: portainer__cloudflared_internet

